### ISSUE TITLE
window attention parameter setting

### ISSUE THREAD

**Issue by A-BigBao** [thu-nics/DiTFastAttn#7]
https://github.com/thu-nics/DiTFastAttn/blob/1cbd9519fd77941f5f14f48c1bb66d67132ebab9/run_pixart.py#L80

According to the Readme in flash-attention, the value of window_size should be set window_size=[args.window_size, args.window_size] instead of window_size=[-args.window_size, args.window_size] ?

https://github.com/Dao-AILab/flash-attention/issues/576

**Comment by hahnyuan** [comment]
You are right. This is a bug.
I have reviewed the code of flashattn, and find the code https://github.com/Dao-AILab/flash-attention/blob/083e8f525f1f8e1dde5044afdac79f9588302207/csrc/flash_attn/flash_api.cpp#L113
It means that if the window_size_left < 0, it wil be set to seqlen_k.
We will fix this bug as soon as possible!

**Comment by hahnyuan** [comment]
We have fixed this bug.
